---
title: "Lab 3"
author: "An Bui"
date: "24 January 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#### O. Attach packages.
```{r packages, include = FALSE}
library(tidyverse)
library(boot)
library(naniar)
library(simputation)
```

#### 1. Bootstrapping penguin flipper lengths
```{r data, include = FALSE}
#### read in ####
penguins <- read_csv("penguins.csv")

#### wrangle ####
male_p <- penguins %>% 
  filter(sex == "MALE")
# only 22 obs, questionable for CLT but look at distribution anyway

#### histogram ####
male_p_hist <- ggplot(male_p, aes(x = flipper_length)) +
  geom_histogram(bins = 10)
male_p_hist
# not normally distributed, duh

#### use pull() to subset data for flipper_length ####
flippers <- male_p %>% 
  pull(flipper_length)
# creates a vector of values to more easily use boot package
```

##### Create a function, then do some bootstrapping.
```{r bootstrapping, message = FALSE}
#### create a function ####
# from original sample (n = 22), take 22 observations with replacement for each bootstrap sample, and calculate mean
# function{argument x, index i (bootstrap sample number)} {mean is the function to run on argument x for each i}
mean_fun <- function(x,i) {mean(x[i])}

#### do the bootstrapping ####
# make a new variable to contain bootstrap information
# usually doing more than 10 samples in bootstrapping
# boot(vector, function, R = number of bootstrap samples to take)
boot_10 <- boot(flippers, mean_fun, R = 10)
boot_10
# boot_10$t0 gives mean of samples
# boot_10$t gives means of all samples

#### set seed so that each bootstrap gives same results ####
set.seed(10)
boot_10 <- boot(flippers, mean_fun, R = 10)
# useful for making reproducible data set

#### try with 100 samples ####
boot_100 <- boot(flippers, mean_fun, R = 100)
# bias and SD change as you increase samples

#### plot distribution of means ####
# ggplot doesn't like vectors, so work around by putting aes() outside ggplot()
flip_dist_hist <- ggplot() +
  aes(boot_100$t) +
  geom_histogram()
flip_dist_hist

#### 5000 samples ####
boot_10000 <- boot(flippers, mean_fun, R = 10000)
boot_10000

#### plot distribution of 10000 ####
flip_dist_hist_10000 <- ggplot() +
  aes(boot_10000$t) +
  geom_histogram()
flip_dist_hist_10000
# ostensibly better BUT IS IT

#### calculate the confidence interval using boot.ci() in boot ####
# give bootstrap and confidence interval you want
boot.ci(boot_10000, conf = 0.95)
```
Again, bootstrapping is a back up to the methods you're already using to verify and validate your original sample - not a replacement for actually collecting data.

#### 2. Evaluating missingness with naniar
```{r missingness, message = FALSE}
#### summary of missingness ####
vis_miss(airquality)
# see if missingness aligns across multiple variables
# also tells you proportions within variables of missing

#### visualize missings by variable ####
gg_miss_var(airquality, facet = Month)
# counts of missings by variable and breaks up by month

#### scatterplot with missing values using geom_miss_point ####
airqual_point_nomiss <- ggplot(airquality, aes(x = Ozone, y = Solar.R)) +
  geom_point()
airqual_point_nomiss

airqual_point_miss <- ggplot(airquality, aes(x = Ozone, y = Solar.R)) +
  geom_miss_point()
airqual_point_miss
# automatically colors values where Solar.R was measured, but without any value for Ozone on y-axis
# where Ozone was measured but not Solar.R along x-axis

#### look at facets ####
airqual_facets <- ggplot(airquality, aes(x = Solar.R, y = Temp)) +
  geom_miss_point() +
  scale_color_manual(values = c("orange", "purple")) +
  facet_wrap(~Month)
airqual_facets
# broken down, you can start asking questions about the tendency of missings dependent on variables separated by groups

#### create shadow matrix ####
# dataframe that contains info about whether or not a value is NA that you can use to visualize those observations


```







